#!/bin/bash
cd web;
drush -y make profiles/lp/lp_drupal_core.make
cd profiles/lp/;
drush -y make --no-core --contrib-destination=. lp.make
#rm -rf modules/ns_core
#rm -rf themes/ns_theme
#git clone --branch 7.x-2.x http://git.drupal.org/project/ns_theme.git themes/ns_theme;
#git clone --branch 7.x-2.x http://git.drupal.org/project/ns_core.git modules/ns_core;
#mkdir sites/default/files
#chmod 777 sites/default/files
echo "done!"
